import React, { Component } from 'react';
import { connect } from 'react-redux';
import AccessoryButtons from '../AccessoryButtons/AccessoryButtons';
import { updateAccessoryDb } from '../../../actions';
import styled from 'styled-components';

const AccessoryItem = styled.div`
  grid-column: 1/5;
  border-top: 1px gray solid;
  border-bottom: 1px gray solid;
  display: grid;
  grid-template-columns: 1fr repeat(3, 3fr);
  align-items: center;
  @media (max-width: 800px) {
    grid-template-columns: 2fr repeat(3, 3fr);
  }
`;

const AccessoryItemContent = styled.div`
  grid-column: 2/5;
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  width: 100%;
  min-height: 50px;
  justify-items: center;
  align-items: center;
  > span {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 50px;
  }
  > input {
    height: 20px;
    width: 100px;
    max-width: 200px;
    text-align: center;
  }
`;

const AccessorySetRep = styled.div`
  grid-column: 2;
  display: flex;
  flex: 1;
  min-height: 50px;
  justify-content: space-evenly;
  align-items: center;
  > input {
    flex: 1;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 20px;
    width: 20px;
    max-width: 100px;
    text-align: center;
  }
`;
class AccessoryRow extends Component {
  state = {
    id: 0,
    title: '',
    sets: 0,
    reps: 0,
    weight: 0,
    currentlyEditing: false,
    loaded: false,
  };

  componentDidMount = async () => {
    console.log(this.props);
    const { id } = this.props;
    //If row is generated by 'add accessory button', start in editing mode
    if (!id) await this.setState({ currentlyEditing: true });
    this.setState({ loaded: true });
  };

  addAcc = () => {
    const { title, sets, reps, weight } = this.state;
    const {
      dispatch,
      accessories,
      dayIndex,
      id,
      userAuth: { userId },
      accessories: { accessoryPlan },
    } = this.props;
    const payload = { title, sets, reps, weight, userId, dayIndex, id };
    dispatch(updateAccessoryDb(payload, 'add', accessories[accessoryPlan], accessoryPlan));
  };

  deleteAcc = () => {
    const {
      dispatch,
      accessories,
      dayIndex,
      id,
      userAuth: { userId },
      accessories: { accessoryPlan },
    } = this.props;
    const payload = { userId, id, dayIndex };
    dispatch(updateAccessoryDb(payload, 'delete', accessories[accessoryPlan], accessoryPlan));
  };

  editAcc = async () => {
    if (this.props.id === undefined) {
      this.addAcc();
      return;
    }
    if (this.state.currentlyEditing) {
      const {
        dispatch,
        accessories,
        dayIndex,
        userAuth: { userId },
        accessories: { accessoryPlan },
      } = this.props;
      const { title, sets, reps, weight, id } = this.state;
      const payload = { title, sets, reps, weight, id, userId, dayIndex };
      await dispatch(updateAccessoryDb(payload, 'edit', accessories[accessoryPlan], accessoryPlan));
      this.setState({ currentlyEditing: false });
    } else {
      const { title, sets, reps, weight, id } = this.props;
      this.setState({ currentlyEditing: true, title, sets, reps, weight, id });
    }
  };

  onChange = e => {
    const { name, value } = e.target;
    this.setState({ [name]: value });
  };

  render() {
    const {
      userAuth,
      title,
      sets,
      reps,
      weight,
      id,
      accessories: { custom, accessoryPlan },
    } = this.props;
    const { loaded } = this.state;
    const showButtons = accessoryPlan === 'custom' || !custom || !id;
    return (
      <AccessoryItem>
        {userAuth.loggedIn && showButtons && loaded && (
          <AccessoryButtons
            deleteAcc={this.deleteAcc}
            addAcc={this.addAcc}
            editAcc={this.editAcc}
            id={id}
            clicked={this.state.currentlyEditing}
            toggleAddBox={this.props.toggleAddBox}
          />
        )}

        {this.state.currentlyEditing ? (
          <AccessoryItemContent>
            <input
              autoFocus="true"
              onChange={this.onChange}
              type="text"
              name={'title'}
              value={this.state.title}
            />
            <AccessorySetRep>
              <input onChange={this.onChange} type="number" name={'sets'} value={this.state.sets} />
              <input onChange={this.onChange} type="number" name={'reps'} value={this.state.reps} />
            </AccessorySetRep>
            <input
              onChange={this.onChange}
              type="number"
              name={'weight'}
              value={this.state.weight}
            />
          </AccessoryItemContent>
        ) : (
          <AccessoryItemContent>
            <span>{title}</span>
            <span>
              {sets} x {reps}
            </span>
            <span>{weight}</span>
          </AccessoryItemContent>
        )}
      </AccessoryItem>
    );
  }
}

const mapStateToProps = state => ({
  accessories: state.accessories,
  userAuth: state.userAuth,
});

export default connect(mapStateToProps)(AccessoryRow);
